name: lingueye
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-444.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  google_mlkit_language_id: ^0.5.0
  google_mlkit_text_recognition: ^0.5.0
  google_mlkit_translation: ^0.5.0
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  provider: ^6.0.5
  circle_flags: ^1.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: false
  image_path: "dev_assets/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
